from .queries.list import query_list
from .queries.form import queries_form
from .queries.details import query_details
from .auth.logout import logout_user
from .agents.form import agents_form
from .agents.list import agent_list
from .books.list import book_list
from .books.form import book_form
from .agents.details import agent_details
from .agents.form import agent_edit_form